mini_proj_CRM/lacrm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import landing_page

urlpatterns = [
    # 'admin/' specfies the route and the admin.site.urls is view that handle the request to this route
    path('admin/', admin.site.urls),
    # landing page url, with name to create link within other templates to redirect to the landing page
    path('',landing_page,name='landing-page'),
    # 📝:IMP including then url path for leads/ prefixed routes by reff to the leads/urls.py in leads app with namespace
    path('leads/', include('leads.urls', namespace="leads"))
]

mini_proj_CRM/leads/urls.py
from turtle import home
from django.urls import path
from .views import lead_create, lead_list, lead_detail, lead_update, lead_delete

app_name = "leads"

urlpatterns = [
    path('',lead_list, name='lead-list'),
    # the pk in the leads will help to dynamically navigate to specific route and show that lead detail
    # 📝: IMP int datatype specified so django do not confuses the path after <pk> routes expecting primary key in the create route
    # 📝: IMP the name passed as third param can be used to refference to the path by using the names instead of passing harcoded url path
    path('<int:pk>/',lead_detail, name='lead-detail'),
    path('create-a-lead/',lead_create, name='lead-create'),
    path('<int:pk>/update/',lead_update, name='lead-update'),
    path('<int:pk>/delete/',lead_delete, name='lead-delete'),
]

mini_proj_CRM/leads/models.py
from django.db import models
# 📝:IMP get user model is a function to grab user model by django
from django.contrib.auth.models import AbstractUser

# inherit AbstractUser from django
class User(AbstractUser):
    # if u dont intend to add anything new to the baseAbstractClass for user by django
    pass
    #📝 in future if additional schema for user is required it can be added here

class Lead(models.Model):
# Model class props inherited in Lead class so it act as now a model class
    # db model define here

    # SOURCE_CHOICES = (
    #     # the first value gets stored in DB while second is the display value
    #     # its always better to make first value as short abbrevation as it will take less space in DB
    #     ('YT','YouTube'),
    #     ('GOG','Google'),
    #     ('NL','Newsletter'),
    # )
    first_name = models.CharField(max_length=20) # first_name restricts to string of CharField
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0) # whole integer

    # phoned = models.BooleanField(default=False) # boolean value
    # source = models.CharField(choices=SOURCE_CHOICES, max_length=100) # multiple choices as tupple NOTE - these values can get overrided though its not a constraint that source only has three possible options

    # profile_picture is optional as we have set blank=True
    # profile_picture = models.ImageField(blank=True,null=True) # blank True means empty string, null means that their is no value in database
    # special_files = models.FileField() # files, it is actually reff to the actual file stored in DB

    #📝 COMPLEX RELATIONSHIPS TABLE COLUMNS
    # FOREIGN KEY
    agent = models.ForeignKey("Agent",on_delete=models.CASCADE)# 📝 "Agent" string is written to make ref to the Agent class even if Agent class was declared/defined after the Leads class

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

# added user to the Agent as Agent is going to login in the system(CRM) not the leads
class Agent(models.Model):
    # 📝 on_delete=CASCADE so if a user is deleted than that agent will be deleted as well
    # 📝 to have 1-1 relation i.e 1 user has exactly 1 agent related to it we use OneToOneField and it works exactly like forign key just the diff is that the relation is 1-1 strict only rather in case of foreign keys where 1 user could have multiple agents
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    #📝:IMP string representation that returns the user email for Agent model when model manager is called on Agent via Agent.objects.all() in shell
    def __str__(self):
        return self.user.email

mini_proj_CRM/leads/forms.py
from django import forms
from .models import Lead

# 📝: model Form
class LeadModelForm(forms.ModelForm):
    # meta class where we specify the information about the form
    class Meta:
        model = Lead # model we are using
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
        ) # tupple of fields in the form that are


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)

mini_proj_CRM/leads/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# 📝 .models refers to relative import as we are inside the lead app
from .models import Agent, Lead
from .forms import LeadForm, LeadModelForm

# landing page
def landing_page(request):
    return render(request, "landing.html")

# Create your views here.
def lead_list(request):
    # where leads is a list of object
    leads = Lead.objects.all()
    context ={
        "leads": leads
    }
    return render(request, "leads/lead_list.html", context)

def lead_detail(request,pk):
    # pk is the route path that can be reffernced to the pk in the leads table
    print(pk)
    lead = Lead.objects.get(id=pk)
    print(lead)
    context = {
        "lead": lead
    }
    return render(request,"leads/lead_detail.html", context)

# using LeadModelForm to create a new Lead
def lead_create(request):
    # initially an empty instantiated form
    form = LeadModelForm()
    print(request.POST)
    if request.method == "POST":
        print('Receiving a post request')
        # populate the form with the data filled and grabbed in request.POST
        form = LeadModelForm(request.POST)
        # is_valid makes sure all the data in the form is validated with proper types and so...
        if form.is_valid():
            # 🎯 abstract away all repeated logic automatically saves data from form to db
            form.save()
            # redirects to the leads page showing all leads
            return redirect("/leads")
    context = {
        # 📝: instantiating the form imported from django
        # to pass it as context to create view/route create new Lead
        "form": form
    }
    return render(request, "leads/lead_create.html", context)

# Using LeadModelForm to update existing lead
def lead_update(request, pk):
    lead = Lead.objects.get(id=pk)
    # 🎯 passing the instace is lead of the model we want to update
    # this will prepopulate the form with current values
    form = LeadModelForm(instance=lead)
    if request.method == "POST":
        # 🎯 populate the form with new values from request.POST and update them for instance lead
        form = LeadModelForm(request.POST, instance=lead)
        print('Receiving a post request')
        if form.is_valid():
            form.save()
            return redirect("/leads")
    context = {
        "form": form,
        "lead": lead
    }
    return render(request,"leads/lead_update.html", context)

# delete a lead from DB
def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    # delete the instance lead with specific id
    lead.delete()
    return redirect("/leads")



# using Simple LeadForm to update lead
# def lead_update(request, pk):
#     lead = Lead.objects.get(id=pk)
#     form = LeadForm()
#     print(request.POST)
#     if request.method == "POST":
#         print('Receiving a post request')
#         # populate the form with the data filled and grabbed in request.POST
#         form = LeadForm(request.POST)
#         # is_valid makes sure all the data in the form is validated with proper types and so...
#         if form.is_valid():
#             print("form data is valid")
#             # cleaned_data is formatted data in dictionary format key:value pairs
#             print(form.cleaned_data)
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             # 🎯update each field for the lead from the form data
#             lead.first_name = first_name
#             lead.last_name = last_name
#             lead.age = age
#             lead.save()
#             print("The lead was updated.",lead)
#             # redirects to the leads page showing all leads
#             return redirect("/leads")
#     context = {
#         "form": form,
#         "lead": lead
#     }
#     return render(request, "leads/lead_update.html", context)


# using Simple LeadForm to create new lead
# def lead_create(request):
#     # initially an empty instantiated form
#     form = LeadForm()
#     print(request.POST)
#     if request.method == "POST":
#         print('Receiving a post request')
#         # populate the form with the data filled and grabbed in request.POST
#         form = LeadForm(request.POST)
#         # is_valid makes sure all the data in the form is validated with proper types and so...
#         if form.is_valid():
#             print("form data is valid")
#             # cleaned_data is formatted data in dictionary format key:value pairs
#             print(form.cleaned_data)
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             # 📝:objects.first() grabs the forst row in the Agent table
#             agent = Agent.objects.first()
#             # creating a new lead with form data
#             Lead.objects.create(
#                 first_name=first_name,
#                 last_name=last_name,
#                 age=age,
#                 agent=agent
#             )
#             print("A new lead was created.")
#             # redirects to the leads page showing all leads
#             return redirect("/leads")
#     context = {
#         # 📝: instantiating the form imported from django
#         # to pass it as context to create view/route create new Lead
#         "form": form
#     }
#     return render(request, "leads/lead_create.html", context)

mini_proj_CRM/leads/templates/leads/lead_create.html
{% extends "base.html" %} {% block content %}
<a href="{% url 'leads:lead-list' %}">Go back to leads</a>
<hr />
<h1>Create a new lead..</h1>
<!--The csrf_token in django generate an hidden csrf middleware that is provided for security by django and used in respect to POST information-->
<form method="post">
  {% csrf_token %} {{form.as_p}}
  <button type="submit">Submit</button>
</form>
{% endblock content %}

mini_proj_CRM/leads/templates/leads/lead_detail.html
{% extends "base.html" %} {% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{lead.first_name}} {{lead.last_name}}
        </h1>
        <div class="flex mb-4">
          <a
            href="{% url 'leads:lead-detail' lead.pk %}"
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Overview</a
          >
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Reviews</a
          >
          <a
            href="{% url 'leads:lead-update' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Update Details</a
          >
        </div>
        <p class="leading-relaxed mb-4">
          Fam locavore kickstarter distillery. Mixtape chillwave tumeric
          sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps
          cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine
          tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.
        </p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{lead.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">Dummy location</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Phone No.</span>
          <span class="ml-auto text-gray-900">98734837431</span>
        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl text-gray-900"
            >$58.00</span
          >
          <button
            class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
          >
            Button
          </button>
          <button
            class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4"
          >
            <svg
              fill="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-5 h-5"
              viewBox="0 0 24 24"
            >
              <path
                d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"
              ></path>
            </svg>
          </button>
        </div>
      </div>
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>
{% endblock content %}

mini_proj_CRM/leads/templates/leads/lead_list.html
{% extends "base.html" %} {% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div
      class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200"
    >
      <div>
        <h1 class="text-4xl text-gray-800">Leads</h1>
      </div>
      <div>
        <a
          class="text-gray-500 hover:text-blue-500"
          href="{% url 'leads:lead-create' %}"
          >Create a new lead</a
        >
      </div>
    </div>
    <div class="flex flex-wrap -m-4">
      {% for lead in leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div
          class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col"
        >
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0"
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-8 h-8"
              viewBox="0 0 24 24"
            >
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{ lead.first_name }} {{ lead.last_name}}
            </h2>
            <p class="leading-relaxed text-base">
              Blue bottle crucifix vinyl post-ironic four dollar toast vegan
              taxidermy. Gastropub indxgo juice poutine.
            </p>
            <a
              href="{% url 'leads:lead-detail' lead.pk %}"
              class="mt-3 text-indigo-500 inline-flex items-center"
              >View this lead
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}

mini_proj_CRM/leads/templates/leads/lead_update.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{lead.first_name}} {{lead.last_name}}
        </h1>
        <div class="flex mb-4">
          <a
            href="{% url 'leads:lead-detail' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Overview</a
          >
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Reviews</a
          >
          <a
            href="{% url 'leads:lead-update' lead.pk %}"
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Update Details</a
          >
        </div>
        <form method="post">
          {% csrf_token %} {{form.as_p}}
          <button type="submit">Submit</button>
        </form>
        <a
          href="{% url 'leads:lead-delete' lead.pk %}"
          class="w=1/2 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
        >
          Delete
        </a>
      </div>
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>
{% endblock content %}